#!/bin/bash

if [ $# -eq 1 ];then
	password=$1
	/show/listecho "Change password to $password" $OK
	/string/replaceLine "/etc/hostapd/hostapd.conf" "wpa_passphrase=" "wpa_passphrase=$password" ""
	service hostapd restart
fi
